[package]
name = "CanOpenDataViewer"
version = "0.1.0"
edition = "2024"

[dependencies]
configparser = "3.1.0"
eframe = "0.31.0"
rfd = "0.15.4"
egui_plot = "0.31.0"
image = "0.25.1"
chrono = "0.4.41"
